### ISSUE TITLE
dependency resolution issue

### ISSUE THREAD

**Issue by monkeygroover** [MfgLabs/precepte#3]
when both importing to IntelliJ and also running sbt gen-ensime i'm getting the following error:

[error] (influx/*:update) sbt.ResolveException: unresolved dependency: com.typesafe.netty#netty-http-pipelining;1.1.2: not found

cheers

**Comment by monkeygroover** [comment]
https://github.com/typesafehub/netty-http-pipelining/issues/13

**Comment by jto** [comment]
Précepte is not pulling that dependency, in fact Précepte has very few dependencies so it's likely to be an issue in either IntelliJ or sbt-ensime.

Here's a list of all Précepte's dependencies (from `show dependencyClasspath`):
```
scala-library-2.11.7.jar
scala-reflect-2.11.7.jar
scalaz-core_2.11-7.1.0.jar
scala-parser-combinators_2.11-1.0.2.jar
scala-xml_2.11-1.0.2.jar
shapeless_2.11-2.2.4.jar
```

**Comment by monkeygroover** [comment]
Hi, if it is then it's an issue in BOTH of them, I think the problem is the other sections in the build.sbt..  some more info in case it shows any more detail:

[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.netty#netty-http-pipelining;1.1.2: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          com.typesafe.netty:netty-http-pipelining:1.1.2
[warn]            +- com.typesafe.play:play_2.11:2.3.9
[warn]            +- com.typesafe.play:play-ws_2.11:2.3.9 (/home/vagrant/my_projects/precepte/build.sbt#L85)
[warn]            +- com.mfglabs:precepte-influx_2.11:0.1.4-SNAPSHOT
sbt.ResolveException: unresolved dependency: com.typesafe.netty#netty-http-pipelining;1.1.2: not found

as far as i can tell this is being pulled in by a play dependency or precepte-influx_2.11:0.1.4-SNAPSHOT?  i can see these in the play/influx sections of the build.sbt file if i comment out these sections it works:

**Comment by jto** [comment]
uh ok so it must be transitively pulled by precepte-play. Have you seen this problem mentioned on play's mailing list ?

**Comment by monkeygroover** [comment]
I've only seen the comments in this thread, https://github.com/typesafehub/netty-http-pipelining/issues/13 but not had time yet to dig into it! i'll take a look later :)
